"""add dimensions to warehouses

Revision ID: 21d56f6bfc4a
Revises: 9b2fb6bfe860
Create Date: 2026-07-25 10:39:41.046191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21d56f6bfc4a'
down_revision: Union[str, Sequence[str], None] = '9b2fb6bfe860'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouses', sa.Column('dimensions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warehouses', 'dimensions')
    # ### end Alembic commands ###
