"""add manual_occupancy to warehouses

Revision ID: 52cc35b8d5c8
Revises: 21d56f6bfc4a
Create Date: 2026-07-26 10:49:48.752213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52cc35b8d5c8'
down_revision: Union[str, Sequence[str], None] = '21d56f6bfc4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouses', sa.Column('manual_occupancy', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warehouses', 'manual_occupancy')
    # ### end Alembic commands ###
