"""create layouts table

Revision ID: 8104aea2e1ba
Revises: 
Create Date: 2026-07-10 19:35:57.341973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8104aea2e1ba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('layouts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.String(), nullable=False),
    sa.Column('constraint_inputs', sa.JSON(), nullable=False),
    sa.Column('optimized_layout', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_layouts_warehouse_id'), 'layouts', ['warehouse_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_layouts_warehouse_id'), table_name='layouts')
    op.drop_table('layouts')
    # ### end Alembic commands ###
